
GET http://localhost:4000/api/recipes/5eb81b79d230551ec0e76318

###

POST http://localhost:4000/api/recipes
Content-Type: application/json

{
    "title": "Gott med grönt",
    "ingredients": "5 veganägg och en banan",
    "howTo": "Denna smoothie innehåller mängder med antioxidanter och järn! Allt som man kan behöva i dessa tider. ",
    "postDate": "5 juni"
}

###

GET http://localhost:4000/api/recipes

###

DELETE http://localhost:4000/api/recipes/

###

PUT  http://localhost:4000/api/recipes/5eb827c2ca149b1320cb2f48
Content-Type: application/json

{
    "_id": "5eb827c2ca149b1320cb2f48",
    "title": "Grönt är skönt",
    "content": "Denna smoothie innehåller mängder med antioxidanter och järn! Allt som man kan behöva i dessa tider. ",
    "postDate": "12 juni",
    "__v": 0
}
